[CXF-8378]:Fix NoClassDefFoundError: org/apache/cxf/common/util/ReflectionUtil (#729)
(cherry picked from commit e320dc1b7f73d3f1190a37f5363846353aa99498)